// Code generated by protoc-gen-go.
// source: priceManager.proto
// DO NOT EDIT!

/*
Package priceManagerClient is a generated protocol buffer package.

It is generated from these files:
	priceManager.proto

It has these top-level messages:
	ChangeLatestRequest
	ProductEntry
	ChangeLatestResponse
	FetchRecordsRequest
	FetchRecordsResponse
	ChangeStatusRequest
	ChangeStatusResponse
*/
package priceManagerClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeLatestRequest struct {
	ProductId []int32 `protobuf:"varint,1,rep,packed,name=productId" json:"productId,omitempty"`
}

func (m *ChangeLatestRequest) Reset()                    { *m = ChangeLatestRequest{} }
func (m *ChangeLatestRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeLatestRequest) ProtoMessage()               {}
func (*ChangeLatestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChangeLatestRequest) GetProductId() []int32 {
	if m != nil {
		return m.ProductId
	}
	return nil
}

type ProductEntry struct {
	ProductId int32  `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *ProductEntry) Reset()                    { *m = ProductEntry{} }
func (m *ProductEntry) String() string            { return proto.CompactTextString(m) }
func (*ProductEntry) ProtoMessage()               {}
func (*ProductEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductEntry) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ProductEntry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ChangeLatestResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ChangeLatestResponse) Reset()                    { *m = ChangeLatestResponse{} }
func (m *ChangeLatestResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeLatestResponse) ProtoMessage()               {}
func (*ChangeLatestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChangeLatestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FetchRecordsRequest struct {
}

func (m *FetchRecordsRequest) Reset()                    { *m = FetchRecordsRequest{} }
func (m *FetchRecordsRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRecordsRequest) ProtoMessage()               {}
func (*FetchRecordsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FetchRecordsResponse struct {
	Products []*ProductEntry `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (m *FetchRecordsResponse) Reset()                    { *m = FetchRecordsResponse{} }
func (m *FetchRecordsResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchRecordsResponse) ProtoMessage()               {}
func (*FetchRecordsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FetchRecordsResponse) GetProducts() []*ProductEntry {
	if m != nil {
		return m.Products
	}
	return nil
}

type ChangeStatusRequest struct {
	Products []*ProductEntry `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (m *ChangeStatusRequest) Reset()                    { *m = ChangeStatusRequest{} }
func (m *ChangeStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeStatusRequest) ProtoMessage()               {}
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChangeStatusRequest) GetProducts() []*ProductEntry {
	if m != nil {
		return m.Products
	}
	return nil
}

type ChangeStatusResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ChangeStatusResponse) Reset()                    { *m = ChangeStatusResponse{} }
func (m *ChangeStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeStatusResponse) ProtoMessage()               {}
func (*ChangeStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChangeStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChangeLatestRequest)(nil), "priceManagerClient.ChangeLatestRequest")
	proto.RegisterType((*ProductEntry)(nil), "priceManagerClient.ProductEntry")
	proto.RegisterType((*ChangeLatestResponse)(nil), "priceManagerClient.ChangeLatestResponse")
	proto.RegisterType((*FetchRecordsRequest)(nil), "priceManagerClient.FetchRecordsRequest")
	proto.RegisterType((*FetchRecordsResponse)(nil), "priceManagerClient.FetchRecordsResponse")
	proto.RegisterType((*ChangeStatusRequest)(nil), "priceManagerClient.ChangeStatusRequest")
	proto.RegisterType((*ChangeStatusResponse)(nil), "priceManagerClient.ChangeStatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PriceManager service

type PriceManagerClient interface {
	SwitchToLatestVersion(ctx context.Context, in *ChangeLatestRequest, opts ...grpc.CallOption) (*ChangeLatestResponse, error)
	GetPriceUpdateRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error)
	ChangeStatusToPicked(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error)
	ChangeStatusToCompleted(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error)
}

type priceManagerClient struct {
	cc *grpc.ClientConn
}

func NewPriceManagerClient(cc *grpc.ClientConn) PriceManagerClient {
	return &priceManagerClient{cc}
}

func (c *priceManagerClient) SwitchToLatestVersion(ctx context.Context, in *ChangeLatestRequest, opts ...grpc.CallOption) (*ChangeLatestResponse, error) {
	out := new(ChangeLatestResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/SwitchToLatestVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) GetPriceUpdateRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error) {
	out := new(FetchRecordsResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/GetPriceUpdateRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) ChangeStatusToPicked(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error) {
	out := new(ChangeStatusResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/ChangeStatusToPicked", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) ChangeStatusToCompleted(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error) {
	out := new(ChangeStatusResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/ChangeStatusToCompleted", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PriceManager service

type PriceManagerServer interface {
	SwitchToLatestVersion(context.Context, *ChangeLatestRequest) (*ChangeLatestResponse, error)
	GetPriceUpdateRecords(context.Context, *FetchRecordsRequest) (*FetchRecordsResponse, error)
	ChangeStatusToPicked(context.Context, *ChangeStatusRequest) (*ChangeStatusResponse, error)
	ChangeStatusToCompleted(context.Context, *ChangeStatusRequest) (*ChangeStatusResponse, error)
}

func RegisterPriceManagerServer(s *grpc.Server, srv PriceManagerServer) {
	s.RegisterService(&_PriceManager_serviceDesc, srv)
}

func _PriceManager_SwitchToLatestVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).SwitchToLatestVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/SwitchToLatestVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).SwitchToLatestVersion(ctx, req.(*ChangeLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_GetPriceUpdateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).GetPriceUpdateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/GetPriceUpdateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).GetPriceUpdateRecords(ctx, req.(*FetchRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_ChangeStatusToPicked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).ChangeStatusToPicked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/ChangeStatusToPicked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).ChangeStatusToPicked(ctx, req.(*ChangeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_ChangeStatusToCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).ChangeStatusToCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/ChangeStatusToCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).ChangeStatusToCompleted(ctx, req.(*ChangeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "priceManagerClient.PriceManager",
	HandlerType: (*PriceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchToLatestVersion",
			Handler:    _PriceManager_SwitchToLatestVersion_Handler,
		},
		{
			MethodName: "GetPriceUpdateRecords",
			Handler:    _PriceManager_GetPriceUpdateRecords_Handler,
		},
		{
			MethodName: "ChangeStatusToPicked",
			Handler:    _PriceManager_ChangeStatusToPicked_Handler,
		},
		{
			MethodName: "ChangeStatusToCompleted",
			Handler:    _PriceManager_ChangeStatusToCompleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "priceManager.proto",
}

func init() { proto.RegisterFile("priceManager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x4b, 0x72, 0x41,
	0x14, 0xd6, 0x57, 0xde, 0xca, 0x53, 0xab, 0x51, 0x49, 0xa2, 0x40, 0x66, 0x93, 0x2b, 0x09, 0xdd,
	0xb6, 0x93, 0x92, 0xa0, 0x40, 0xae, 0xd6, 0x36, 0xa6, 0x7b, 0x0f, 0x3a, 0xa8, 0x33, 0xd3, 0xcc,
	0xb1, 0xe8, 0x17, 0xf6, 0xb7, 0xe2, 0x7e, 0x69, 0x43, 0x83, 0x2e, 0xa2, 0xe5, 0x39, 0xf7, 0xcc,
	0xf3, 0xc9, 0x05, 0x66, 0xac, 0x8c, 0xf1, 0x41, 0x28, 0x31, 0x43, 0xdb, 0x33, 0x56, 0x93, 0x66,
	0xde, 0x6e, 0xb8, 0x94, 0xa8, 0x88, 0x0f, 0xa0, 0x31, 0x9c, 0x0b, 0x35, 0xc3, 0x7b, 0x41, 0xe8,
	0x28, 0xc2, 0xd7, 0x35, 0x3a, 0x62, 0xe7, 0x50, 0x37, 0x56, 0x27, 0xeb, 0x98, 0xee, 0x92, 0x76,
	0xb5, 0x53, 0xeb, 0xfe, 0x8f, 0xb6, 0x0b, 0x3e, 0x82, 0x93, 0x71, 0x3e, 0xdc, 0x28, 0xb2, 0x1f,
	0xec, 0x02, 0xa0, 0xf8, 0xf8, 0x2c, 0xd3, 0xf3, 0xaa, 0x77, 0xce, 0xda, 0x70, 0xf8, 0x86, 0xd6,
	0x49, 0xad, 0xda, 0xff, 0x3a, 0xd5, 0x6e, 0x3d, 0x2a, 0x47, 0x7e, 0x05, 0x4d, 0x9f, 0xdd, 0x19,
	0xad, 0x1c, 0xa6, 0x2f, 0x56, 0xe8, 0x9c, 0x98, 0x61, 0x86, 0x56, 0x8f, 0xca, 0x91, 0xb7, 0xa0,
	0x71, 0x8b, 0x14, 0xcf, 0x23, 0x8c, 0xb5, 0x4d, 0x5c, 0xa1, 0x97, 0x4f, 0xa1, 0xe9, 0xaf, 0x0b,
	0xa0, 0x6b, 0x38, 0x2a, 0x74, 0xb8, 0xcc, 0xc6, 0x71, 0xbf, 0xd3, 0xfb, 0x99, 0x42, 0xef, 0xbb,
	0x9b, 0x68, 0xf3, 0x82, 0x4f, 0xca, 0x70, 0x26, 0x24, 0x68, 0x5d, 0x92, 0xfd, 0x12, 0x74, 0xe3,
	0xb9, 0x04, 0xdd, 0xe7, 0xb9, 0xff, 0x59, 0x4b, 0xf3, 0xde, 0xe2, 0xb3, 0x25, 0xb4, 0x26, 0xef,
	0x92, 0xe2, 0xf9, 0x54, 0xe7, 0xc1, 0x3d, 0xe5, 0x79, 0xb2, 0xcb, 0x90, 0x8e, 0x40, 0xbf, 0x67,
	0xdd, 0xfd, 0x87, 0xb9, 0x2c, 0x5e, 0x49, 0xd9, 0x46, 0x48, 0x99, 0x80, 0x47, 0x93, 0x08, 0xc2,
	0x22, 0xe4, 0x30, 0x5b, 0xa0, 0x9d, 0x30, 0x5b, 0xa8, 0x2f, 0x5e, 0x61, 0x0b, 0x3f, 0x9e, 0xa9,
	0x1e, 0xcb, 0x78, 0x81, 0xc9, 0x2e, 0x6b, 0x5e, 0x3b, 0xbb, 0xac, 0xf9, 0x89, 0xf3, 0x0a, 0x53,
	0x70, 0xea, 0x93, 0x0d, 0xf5, 0xca, 0x2c, 0x91, 0xfe, 0x88, 0xef, 0xe5, 0x20, 0xfb, 0x11, 0x07,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xaf, 0x3b, 0x21, 0x9e, 0x03, 0x00, 0x00,
}
