// Code generated by protoc-gen-go.
// source: priceManager.proto
// DO NOT EDIT!

/*
Package priceManagerClient is a generated protocol buffer package.

It is generated from these files:
	priceManager.proto

It has these top-level messages:
	Entry
	FetchRecordsRequest
	FetchRecordsResponse
	NotifyRequest
	NotifyResponse
*/
package priceManagerClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	ProductId int32  `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Entry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type FetchRecordsRequest struct {
}

func (m *FetchRecordsRequest) Reset()                    { *m = FetchRecordsRequest{} }
func (m *FetchRecordsRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRecordsRequest) ProtoMessage()               {}
func (*FetchRecordsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FetchRecordsResponse struct {
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *FetchRecordsResponse) Reset()                    { *m = FetchRecordsResponse{} }
func (m *FetchRecordsResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchRecordsResponse) ProtoMessage()               {}
func (*FetchRecordsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FetchRecordsResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type NotifyRequest struct {
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *NotifyRequest) Reset()                    { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()               {}
func (*NotifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NotifyRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type NotifyResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *NotifyResponse) Reset()                    { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()               {}
func (*NotifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NotifyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "priceManagerClient.Entry")
	proto.RegisterType((*FetchRecordsRequest)(nil), "priceManagerClient.FetchRecordsRequest")
	proto.RegisterType((*FetchRecordsResponse)(nil), "priceManagerClient.FetchRecordsResponse")
	proto.RegisterType((*NotifyRequest)(nil), "priceManagerClient.NotifyRequest")
	proto.RegisterType((*NotifyResponse)(nil), "priceManagerClient.NotifyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PriceManager service

type PriceManagerClient interface {
	GetPriceUpdateRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error)
	NotifySuccessfullyPicked(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	NotifySuccessfullyProcessed(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	GetAllRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error)
}

type priceManagerClient struct {
	cc *grpc.ClientConn
}

func NewPriceManagerClient(cc *grpc.ClientConn) PriceManagerClient {
	return &priceManagerClient{cc}
}

func (c *priceManagerClient) GetPriceUpdateRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error) {
	out := new(FetchRecordsResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/GetPriceUpdateRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) NotifySuccessfullyPicked(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/NotifySuccessfullyPicked", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) NotifySuccessfullyProcessed(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/NotifySuccessfullyProcessed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceManagerClient) GetAllRecords(ctx context.Context, in *FetchRecordsRequest, opts ...grpc.CallOption) (*FetchRecordsResponse, error) {
	out := new(FetchRecordsResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.PriceManager/GetAllRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PriceManager service

type PriceManagerServer interface {
	GetPriceUpdateRecords(context.Context, *FetchRecordsRequest) (*FetchRecordsResponse, error)
	NotifySuccessfullyPicked(context.Context, *NotifyRequest) (*NotifyResponse, error)
	NotifySuccessfullyProcessed(context.Context, *NotifyRequest) (*NotifyResponse, error)
	GetAllRecords(context.Context, *FetchRecordsRequest) (*FetchRecordsResponse, error)
}

func RegisterPriceManagerServer(s *grpc.Server, srv PriceManagerServer) {
	s.RegisterService(&_PriceManager_serviceDesc, srv)
}

func _PriceManager_GetPriceUpdateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).GetPriceUpdateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/GetPriceUpdateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).GetPriceUpdateRecords(ctx, req.(*FetchRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_NotifySuccessfullyPicked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).NotifySuccessfullyPicked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/NotifySuccessfullyPicked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).NotifySuccessfullyPicked(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_NotifySuccessfullyProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).NotifySuccessfullyProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/NotifySuccessfullyProcessed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).NotifySuccessfullyProcessed(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceManager_GetAllRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceManagerServer).GetAllRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.PriceManager/GetAllRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceManagerServer).GetAllRecords(ctx, req.(*FetchRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "priceManagerClient.PriceManager",
	HandlerType: (*PriceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPriceUpdateRecords",
			Handler:    _PriceManager_GetPriceUpdateRecords_Handler,
		},
		{
			MethodName: "NotifySuccessfullyPicked",
			Handler:    _PriceManager_NotifySuccessfullyPicked_Handler,
		},
		{
			MethodName: "NotifySuccessfullyProcessed",
			Handler:    _PriceManager_NotifySuccessfullyProcessed_Handler,
		},
		{
			MethodName: "GetAllRecords",
			Handler:    _PriceManager_GetAllRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "priceManager.proto",
}

func init() { proto.RegisterFile("priceManager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xad, 0x63, 0x8e, 0x5d, 0x9d, 0x0f, 0xd1, 0x41, 0x9c, 0x08, 0x33, 0x2f, 0x16, 0x1f,
	0xf6, 0xb0, 0x7d, 0x01, 0xc5, 0x3f, 0x43, 0x44, 0x19, 0x11, 0x9f, 0xa5, 0x26, 0x77, 0x33, 0x18,
	0x93, 0x9a, 0xa4, 0x42, 0x3f, 0x95, 0x5f, 0x51, 0xec, 0x5a, 0xb1, 0x58, 0x14, 0x44, 0xdf, 0x72,
	0x0f, 0x97, 0x73, 0x7e, 0xf7, 0x10, 0x20, 0xa9, 0x53, 0x02, 0xaf, 0x12, 0x93, 0x2c, 0xd0, 0x8d,
	0x52, 0x67, 0x83, 0x25, 0x35, 0xed, 0x44, 0x2b, 0x34, 0x81, 0x1d, 0x41, 0xfb, 0xcc, 0x04, 0x97,
	0x93, 0x3d, 0x80, 0xd4, 0x59, 0x99, 0x89, 0x70, 0xa7, 0x24, 0x8d, 0x86, 0x51, 0xdc, 0xe6, 0xdd,
	0x52, 0xb9, 0x90, 0x84, 0x42, 0xe7, 0x05, 0x9d, 0x57, 0xd6, 0xd0, 0xd5, 0x61, 0x14, 0x77, 0x79,
	0x35, 0xb2, 0x3e, 0x6c, 0x9d, 0x63, 0x10, 0x0f, 0x1c, 0x85, 0x75, 0xd2, 0x73, 0x7c, 0xce, 0xd0,
	0x07, 0x76, 0x09, 0xdb, 0x75, 0xd9, 0xa7, 0xd6, 0x78, 0x24, 0x13, 0xe8, 0xa0, 0x09, 0x4e, 0xa1,
	0xa7, 0xd1, 0xb0, 0x15, 0xaf, 0x8f, 0x77, 0x46, 0x5f, 0xb1, 0x46, 0x05, 0x13, 0xaf, 0x36, 0xd9,
	0x29, 0xf4, 0xae, 0x6d, 0x50, 0xf3, 0xbc, 0x74, 0xff, 0x9d, 0xcb, 0x21, 0x6c, 0x56, 0x2e, 0x25,
	0x0c, 0x85, 0xce, 0x13, 0x7a, 0x9f, 0x2c, 0xb0, 0xb8, 0xb8, 0xcb, 0xab, 0x71, 0xfc, 0xda, 0x82,
	0x8d, 0xd9, 0x27, 0x47, 0xa2, 0xa1, 0x3f, 0xc5, 0x50, 0x48, 0xb7, 0xa9, 0x4c, 0x02, 0x96, 0x87,
	0x91, 0x83, 0xa6, 0xe4, 0x86, 0x46, 0x06, 0xf1, 0xcf, 0x8b, 0x4b, 0x2c, 0xb6, 0x42, 0x04, 0xd0,
	0x25, 0xea, 0x4d, 0x26, 0x04, 0x7a, 0x3f, 0xcf, 0xb4, 0xce, 0x67, 0x4a, 0x3c, 0xa2, 0x24, 0xfb,
	0x4d, 0x3e, 0xb5, 0x7a, 0x06, 0xec, 0xbb, 0x95, 0x8f, 0x90, 0x39, 0xec, 0x36, 0x84, 0x38, 0xfb,
	0xfe, 0xfe, 0xcb, 0x1c, 0x09, 0xbd, 0x29, 0x86, 0x63, 0xad, 0xff, 0xb3, 0xb2, 0xfb, 0xb5, 0xe2,
	0x93, 0x4f, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xb4, 0x1f, 0xce, 0xfa, 0x02, 0x00, 0x00,
}
