// Code generated by protoc-gen-go.
// source: price.proto
// DO NOT EDIT!

/*
Package priceManagerClient is a generated protocol buffer package.

It is generated from these files:
	price.proto

It has these top-level messages:
	ChangeLatestRequest
	ChangeLatestResponse
*/
package priceManagerClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeLatestRequest struct {
	ProductId []int32 `protobuf:"varint,1,rep,packed,name=productId" json:"productId,omitempty"`
}

func (m *ChangeLatestRequest) Reset()                    { *m = ChangeLatestRequest{} }
func (m *ChangeLatestRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeLatestRequest) ProtoMessage()               {}
func (*ChangeLatestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChangeLatestRequest) GetProductId() []int32 {
	if m != nil {
		return m.ProductId
	}
	return nil
}

type ChangeLatestResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ChangeLatestResponse) Reset()                    { *m = ChangeLatestResponse{} }
func (m *ChangeLatestResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeLatestResponse) ProtoMessage()               {}
func (*ChangeLatestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChangeLatestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChangeLatestRequest)(nil), "priceManagerClient.ChangeLatestRequest")
	proto.RegisterType((*ChangeLatestResponse)(nil), "priceManagerClient.ChangeLatestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Price service

type PriceClient interface {
	SwitchToLatestVersion(ctx context.Context, in *ChangeLatestRequest, opts ...grpc.CallOption) (*ChangeLatestResponse, error)
}

type priceClient struct {
	cc *grpc.ClientConn
}

func NewPriceClient(cc *grpc.ClientConn) PriceClient {
	return &priceClient{cc}
}

func (c *priceClient) SwitchToLatestVersion(ctx context.Context, in *ChangeLatestRequest, opts ...grpc.CallOption) (*ChangeLatestResponse, error) {
	out := new(ChangeLatestResponse)
	err := grpc.Invoke(ctx, "/priceManagerClient.Price/SwitchToLatestVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Price service

type PriceServer interface {
	SwitchToLatestVersion(context.Context, *ChangeLatestRequest) (*ChangeLatestResponse, error)
}

func RegisterPriceServer(s *grpc.Server, srv PriceServer) {
	s.RegisterService(&_Price_serviceDesc, srv)
}

func _Price_SwitchToLatestVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServer).SwitchToLatestVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceManagerClient.Price/SwitchToLatestVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServer).SwitchToLatestVersion(ctx, req.(*ChangeLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Price_serviceDesc = grpc.ServiceDesc{
	ServiceName: "priceManagerClient.Price",
	HandlerType: (*PriceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchToLatestVersion",
			Handler:    _Price_SwitchToLatestVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "price.proto",
}

func init() { proto.RegisterFile("price.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x02, 0x73, 0x7c, 0x13, 0xf3, 0x12, 0xd3,
	0x53, 0x8b, 0x9c, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x94, 0x8c, 0xb9, 0x84, 0x9d, 0x33, 0x12, 0xf3,
	0xd2, 0x53, 0x7d, 0x12, 0x4b, 0x52, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x64, 0xb8, 0x38, 0x0b, 0x8a, 0xf2, 0x53, 0x4a, 0x93, 0x4b, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x98,
	0x35, 0x58, 0x83, 0x10, 0x02, 0x4a, 0x06, 0x5c, 0x22, 0xa8, 0x9a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x60, 0x5c, 0xa3, 0x52, 0x2e, 0xd6, 0x00, 0x90, 0xe5, 0x42, 0x39, 0x5c, 0xa2,
	0xc1, 0xe5, 0x99, 0x25, 0xc9, 0x19, 0x21, 0xf9, 0x10, 0xcd, 0x61, 0xa9, 0x45, 0xc5, 0x99, 0xf9,
	0x79, 0x42, 0xea, 0x7a, 0x98, 0xae, 0xd3, 0xc3, 0xe2, 0x34, 0x29, 0x0d, 0xc2, 0x0a, 0x21, 0xce,
	0x51, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x0e, 0x8b,
	0x4e, 0x07, 0x01, 0x00, 0x00,
}
